'use client';

import { useEffect, useState, type ChangeEvent, type FormEvent } from 'react';

const API = process.env.NEXT_PUBLIC_API_BASE_URL ?? 'http://localhost:4000';
type User = { id: string; email: string; name: string; avatarUrl?: string };
type Sender = { id: string; displayName: string; fromEmail: string };
type Email = { id: string; recipientEmail: string; status: string; scheduledAt: string; sentAt?: string; subject: string; lastError?: string };
type PageMeta = { page: number; totalPages: number; total: number };

async function api(path: string, init: RequestInit = {}) {
  const response = await fetch(`${API}${path}`, { ...init, credentials: 'include', headers: { 'content-type': 'application/json', ...(init.headers ?? {}) } });
  if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.error?.message ?? 'Request failed'); }
  return response.status === 204 ? null : response.json();
}

export default function Home() {
  const [user, setUser] = useState<User | null>(null); const [error, setError] = useState('');
  useEffect(() => { api('/auth/me').then((result) => setUser(result.data)).catch(() => undefined); }, []);
  if (!user) return <main className="auth"><section className="card"><p className="eyebrow">OUTBOX / REACHINBOX</p><h1>Durable email scheduling.</h1><p className="muted">Schedule once. Persist everywhere. Observe every send.</p>{error && <p className="error">{error}</p>}<button onClick={async () => { try { const result = await api('/auth/dev-login', { method: 'POST', body: JSON.stringify({}) }); setUser(result.data); } catch (caught) { setError((caught as Error).message); } }}>Continue with demo account</button><a className="google" href={`${API}/auth/google`}>Use Google OAuth</a></section></main>;
  return <Dashboard user={user} onLogout={() => { api('/auth/logout', { method: 'POST' }).then(() => setUser(null)); }} />;
}

function Dashboard({ user, onLogout }: { user: User; onLogout: () => void }) {
  const [tab, setTab] = useState<'scheduled' | 'sent'>('scheduled'); const [rows, setRows] = useState<Email[]>([]); const [senders, setSenders] = useState<Sender[]>([]); const [meta, setMeta] = useState<PageMeta>({ page: 1, totalPages: 1, total: 0 }); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [showCompose, setShowCompose] = useState(false); const [notice, setNotice] = useState('');
  const reload = () => { setLoading(true); return Promise.all([api(`/emails/${tab}?page=${page}&pageSize=50`).then((result) => { setRows(result.data); setMeta(result.meta); }), api('/senders').then((result) => setSenders(result.data))]).catch((caught) => setNotice((caught as Error).message)).finally(() => setLoading(false)); };
  useEffect(() => { void reload(); const timer = setInterval(() => void reload(), 5000); return () => clearInterval(timer); }, [tab, page]);
  const selectTab = (next: 'scheduled' | 'sent') => { setTab(next); setPage(1); };
  return <main className="shell"><header><div><p className="eyebrow">OUTBOX CONTROL ROOM</p><h1>Mail operations</h1></div><div className="user">{user.avatarUrl ? <img className="avatar" src={user.avatarUrl} alt="" /> : <span className="avatar fallback">{user.name.slice(0, 1)}</span>}<span>{user.name}</span><button className="quiet" onClick={onLogout}>Log out</button></div></header><section className="hero"><div><p className="muted">Welcome back, {user.email}</p><h2>Keep every delivery explainable.</h2></div><button onClick={() => setShowCompose(true)}>+ Compose campaign</button></section>{notice && <p className="error">{notice}</p>}<nav className="tabs"><button className={tab === 'scheduled' ? 'active' : ''} onClick={() => selectTab('scheduled')}>Scheduled</button><button className={tab === 'sent' ? 'active' : ''} onClick={() => selectTab('sent')}>Sent &amp; failed</button></nav><section className="card table-card"><div className="table-head"><div><p className="eyebrow">LIVE STATE</p><h2>{tab === 'scheduled' ? 'Scheduled emails' : 'Delivery history'}</h2></div><span className="pill">{meta.total} total</span></div>{loading ? <div className="empty"><strong>Loading email state…</strong><span>Reading persisted PostgreSQL records.</span></div> : rows.length === 0 ? <div className="empty"><strong>No {tab} emails yet.</strong><span>Compose a campaign to create durable queue jobs.</span></div> : <><div className="table-wrap"><table><thead><tr><th>Recipient</th><th>Subject</th><th>Status</th><th>When</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{row.recipientEmail}</td><td>{row.subject}</td><td><span className={`status ${row.status.toLowerCase()}`}>{row.status}</span>{row.lastError && <small>{row.lastError}</small>}</td><td>{new Date(row.sentAt ?? row.scheduledAt).toLocaleString()}</td></tr>)}</tbody></table></div><div className="pager"><button className="quiet" disabled={page <= 1} onClick={() => setPage(page - 1)}>Previous</button><span>Page {meta.page} of {Math.max(1, meta.totalPages)}</span><button className="quiet" disabled={page >= meta.totalPages} onClick={() => setPage(page + 1)}>Next</button></div></>}</section>{showCompose && <Compose senders={senders} onClose={() => setShowCompose(false)} onDone={() => { setShowCompose(false); setTab('scheduled'); setPage(1); void reload(); }} />}</main>;
}

function parseRecipients(text: string) { const emails = text.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi) ?? []; return [...new Set(emails.map((email) => email.toLowerCase()))]; }

function Compose({ senders, onClose, onDone }: { senders: Sender[]; onClose: () => void; onDone: () => void }) {
  const [subject, setSubject] = useState(''); const [body, setBody] = useState(''); const [recipientText, setRecipientText] = useState(''); const [startAt, setStartAt] = useState(new Date(Date.now() + 60000).toISOString().slice(0, 16)); const [delay, setDelay] = useState(1000); const [limit, setLimit] = useState(200); const [senderId, setSenderId] = useState(senders[0]?.id ?? ''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const recipients = parseRecipients(recipientText); const onFile = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (file) setRecipientText(await file.text()); };
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { if (!recipients.length) throw new Error('Add at least one valid email address'); await api('/emails/schedule', { method: 'POST', body: JSON.stringify({ subject, body, recipients, senderId, startAt: new Date(startAt).toISOString(), delayBetweenEmailsMs: Number(delay), hourlyLimit: Number(limit) }) }); onDone(); } catch (caught) { setError((caught as Error).message); } finally { setBusy(false); } };
  return <div className="backdrop"><form className="modal" onSubmit={submit}><div className="modal-head"><div><p className="eyebrow">NEW CAMPAIGN</p><h2>Schedule emails</h2></div><button type="button" className="quiet" onClick={onClose}>Close</button></div>{error && <p className="error">{error}</p>}<label>Sender<select value={senderId} onChange={(event) => setSenderId(event.target.value)} required>{senders.map((sender) => <option key={sender.id} value={sender.id}>{sender.displayName} · {sender.fromEmail}</option>)}</select></label><label>Subject<input value={subject} onChange={(event) => setSubject(event.target.value)} required maxLength={200} /></label><label>Body<textarea value={body} onChange={(event) => setBody(event.target.value)} required rows={5} /></label><label>Recipients <span className="hint">CSV, TXT, commas, spaces, or newlines</span><input type="file" accept=".csv,.txt,text/csv,text/plain" onChange={onFile} /><textarea value={recipientText} onChange={(event) => setRecipientText(event.target.value)} required rows={4} placeholder="ada@example.com, grace@example.com" /><span className="recipient-count">{recipients.length} valid recipient{recipients.length === 1 ? '' : 's'}</span></label><div className="grid"><label>Start time<input type="datetime-local" value={startAt} onChange={(event) => setStartAt(event.target.value)} required /></label><label>Delay (ms)<input type="number" min="0" value={delay} onChange={(event) => setDelay(Number(event.target.value))} /></label><label>Hourly limit<input type="number" min="1" value={limit} onChange={(event) => setLimit(Number(event.target.value))} /></label></div><button disabled={busy || !senderId}>{busy ? 'Scheduling…' : 'Schedule campaign'}</button></form></div>;
}
