'use client';
import { useState, type ChangeEvent, type FormEvent } from 'react';
import { api } from '../lib/api';
import { parseRecipients } from '../lib/recipients';
type Sender = { id:string; displayName:string; fromEmail:string };
export function ComposeModal({ senders, onClose, onDone }: { senders:Sender[]; onClose:()=>void; onDone:()=>void }) {
  const [subject,setSubject]=useState(''); const [body,setBody]=useState(''); const [recipientText,setRecipientText]=useState(''); const [startAt,setStartAt]=useState(new Date(Date.now()+60000).toISOString().slice(0,16)); const [delay,setDelay]=useState(1000); const [limit,setLimit]=useState(200); const [senderId,setSenderId]=useState(senders[0]?.id ?? ''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const recipients=parseRecipients(recipientText);
  const onFile=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(file)setRecipientText(await file.text());};
  const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError('');try{if(!recipients.length)throw new Error('Add at least one valid email address');await api('/emails/schedule',{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({subject,body,recipients,senderId,startAt:new Date(startAt).toISOString(),delayBetweenEmailsMs:Number(delay),hourlyLimit:Number(limit)})});onDone();}catch(caught){setError((caught as Error).message);}finally{setBusy(false);}};
  return <div className="backdrop"><form className="modal" onSubmit={submit}><div className="modal-head"><div><p className="eyebrow">NEW CAMPAIGN</p><h2>Schedule emails</h2></div><button type="button" className="quiet" onClick={onClose}>Close</button></div>{error&&<p className="error">{error}</p>}<label>Sender<select value={senderId} onChange={event=>setSenderId(event.target.value)} required>{senders.map(sender=><option key={sender.id} value={sender.id}>{sender.displayName} · {sender.fromEmail}</option>)}</select></label><label>Subject<input value={subject} onChange={event=>setSubject(event.target.value)} required maxLength={200}/></label><label>Body<textarea value={body} onChange={event=>setBody(event.target.value)} required rows={5}/></label><label>Recipients <span className="hint">CSV, TXT, commas, spaces, or newlines</span><input type="file" accept=".csv,.txt,text/csv,text/plain" onChange={onFile}/><textarea value={recipientText} onChange={event=>setRecipientText(event.target.value)} required rows={4} placeholder="ada@example.com, grace@example.com"/><span className="recipient-count">{recipients.length} valid recipient{recipients.length===1?'':'s'}</span></label><div className="grid"><label>Start time<input type="datetime-local" value={startAt} onChange={event=>setStartAt(event.target.value)} required/></label><label>Delay (ms)<input type="number" min="1" value={delay} onChange={event=>setDelay(Number(event.target.value))}/></label><label>Sender hourly cap<input type="number" min="1" value={limit} onChange={event=>setLimit(Number(event.target.value))}/></label></div><button disabled={busy||!senderId}>{busy?'Scheduling…':'Schedule campaign'}</button></form></div>;
}
